url: http://localhost:4000
name: Web 3.0, 6 Bladed Razors, 7 Minute Abs
description: A web development blog written by @zachleat.
safe: false
auto: true
baseurl: /web
markdown: rdiscount
# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /web/:title/